### ISSUE TITLE
darwin support ? make mac-build has an error ...

### ISSUE THREAD

**Issue by gedw99** [krotik/ecal#1]
makefile seems to indicate that mac support is wanted.

But when i tried to run it i hit some errors:

```

make build-mac
rm -f ecal
go mod init || true
go: /Users/apple/workspace/go/src/github.com/gerardwebb/research/blockchain/graphdb/krotik__ecal/ecal/go.mod already exists
go mod tidy
go generate devt.de/krotik/ecal/stdlib/generate
Generating ECAL stdlib from Go functions ...
fork/exec /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/go-build757582189/b001/exe/generate: exec format error
stdlib/generate/generate.go:35: running "go": exit status 1
make: *** [generate] Error 1 

```

I have not investigated what's going on yet, but wanted to first make this issue to get feedback..

**Comment by gedw99** [comment]
all the tests for the repo pass on a mac btw.

export GOOS=darwin
```
make test
go test -p 1 ./...
?       devt.de/krotik/ecal/cli [no test files]
ok      devt.de/krotik/ecal/cli/tool    1.242s
ok      devt.de/krotik/ecal/config      0.119s
ok      devt.de/krotik/ecal/engine      0.148s
ok      devt.de/krotik/ecal/engine/pool 0.166s
ok      devt.de/krotik/ecal/engine/pubsub       0.121s
?       devt.de/krotik/ecal/examples/plugin     [no test files]
ok      devt.de/krotik/ecal/interpreter 0.899s
ok      devt.de/krotik/ecal/parser      0.198s
ok      devt.de/krotik/ecal/scope       0.162s
ok      devt.de/krotik/ecal/stdlib      0.210s
ok      devt.de/krotik/ecal/stdlib/generate     2.085s
ok      devt.de/krotik/ecal/util        0.177s
```

**Comment by gedw99** [comment]
so the only reason the make file does not work on a mac is just the "export GOOS=darwin" at the top.

Should we change it to detect it at runtime ?

**Comment by gedw99** [comment]
this is really minor, so just close it if its not worth it

**Comment by mladkau** [comment]
Hey, thanks for raising this! Yes, I would love to have proper Mac support. Unfortunately, I do not have a Mac so I can't really test or debug things. If you have an idea on how to fix this let me know (or raise a PR :smile: )

**Comment by gedw99** [comment]
Actually everyone is working perfectly on mac
build, dist, examples. the whole lots.

dont change anything :)

**Comment by gedw99** [comment]
I just had to do a "brew install coreutils" and link it and the sha256sum did its thing.

I like the setup !!

**Comment by gedw99** [comment]
i think we can close this. If it aint broke dont fix it :)

**Comment by krotik** [comment]
Alright, I'll close it. Thanks for raising and investigating :pray:

**Comment by gedw99** [comment]
Maybe add this to the README if you feel its worth it:

"

For mac users that want to run the ``` make dist ``` 

```
### COREUTILS
#brew install coreutils
# need to add path to make it available
PATH="$(brew --prefix)/opt/coreutils/libexec/gnubin:$PATH"
``` 

"
